name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: 
          - ec2-3-91-95-49.compute-1.amazonaws.com
          - ec2-34-204-107-58.compute-1.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy to EC2
      env:
        SERVER: ${{ matrix.server }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@$SERVER << 'EOF'
          sudo chown -R ec2-user:ec2-user /home/ec2-user/Node-x-Nginx
          cd /home/ec2-user/Node-x-Nginx
          git config --global --add safe.directory /home/ec2-user/Node-x-Nginx
          git reset --hard HEAD
          git pull origin main
          npm install
          sudo pm2 restart my-app 
          sudo systemctl restart nginx
        EOF

    - name: Cleanup
      run: rm private_key