name: Deploy to test

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: 
          - ec2-54-82-65-124.compute-1.amazonaws.com

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Deploy to EC2
      env:
        SERVER: ${{ matrix.server }}
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@$SERVER << 'EOF'
          sudo chown -R ec2-user:ec2-user /home/ec2-user/Node-x-Nginx
          cd /home/ec2-user/Node-x-Nginx
          git config --global --add safe.directory /home/ec2-user/Node-x-Nginx
          git reset --hard HEAD
          git pull origin test
          npm install
          sudo pm2 restart my-app 
          sudo systemctl restart nginx
        EOF